accounts/urls.py
from django.urls import path, include
from . import views

app_name = 'accounts'

urlpatterns = [

    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'), 
    path('logout/', views.Logout_View, name='logout'),

]

backend/urls.py
from django.contrib import admin
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontend.urls', namespace='frontend')), 
    path('accounts/', include('accounts.urls', namespace='accounts')), 
    path('bookings/', include('bookings.urls', namespace='bookings')), 
    path('menu/', include('menu.urls', namespace='menu')), 
]

bookings/urls.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from django.contrib.auth.decorators import login_required
from django.urls import path
from . import views

app_name = 'bookings'

urlpatterns = [
 
    path('booking_dashboard/', views.booking_dashboard_view, name='booking_dashboard'),     
    path('make_booking/', views.make_booking_view, name='make_booking'),
    path('edit_booking/<int:booking_id>/', views.edit_booking_view, name='edit_booking'),     
    path('confirmation/<int:booking_id>/', views.booking_confirmation, name='booking_confirmation'),
    path('cancel/<int:booking_id>/', views.cancel_booking_view, name='cancel_booking'),
    
]

menu/urls.py
from django.urls import path, include
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from . import views

app_name = 'menu'

urlpatterns = [
    path('menu/', views.menu_view, name='menu'),
    path('recipe/', views.recipe_view, name='recipe'),
    path('gallery/', views.gallery_view, name='gallery'),
]

bookings/models.py
from django.db import models
from django.utils import timezone
from datetime import time
from django.conf import settings

# Create your models here.


class Bookings(models.Model):
    
    GUEST_OPTIONS = [(i,str(i)) for i in range(1, 11)]


    
    TIME_SLOTS = [
        (1, "13:00 - 15:00"),
        (2, "15:00 - 17:00"),
        (3, "17:00 - 19:00"),
        (4, "19:00 - 21:00"),
        (5, "21:00 - 22:00"),
        (6, "22:00 - 00:00"),
    ]       
       
       
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='bookings', null=True, blank=True)
    number_of_guests = models.PositiveIntegerField(choices=GUEST_OPTIONS)
    date = models.DateField()
    time_slot = models.IntegerField(choices=TIME_SLOTS, default=1)
    timestamp_booking_made = models.DateTimeField(auto_now=True)
    first_name = models.CharField(max_length=50, null=False, blank=False)
    last_name = models.CharField(max_length=50, null=False, blank=False)    
    email = models.EmailField(max_length=50, null=False, blank=False)
    phone_number = models.CharField(max_length=20, null=False, blank=False) 
    allergy = models.TextField(max_length=20, blank=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name} - {self.date} {self.get_time_slot_display()}"

bookings/forms.py
from datetime import datetime, time
from django.db import models
from django import forms
from django.core.exceptions import ValidationError
from .models import Bookings



class BookingsForm(forms.ModelForm):

    class Meta:
        model = Bookings
        fields = [           
            'number_of_guests',
            'date',
            'time_slot',  
            'first_name',
            'last_name',
            'email',
            'phone_number',
            'allergy'
        ]
        

        widgets = {
            'number_of_guests': forms.NumberInput(attrs={'class': 'form-control', 'min': 1, 'max': 20}),
            'date': forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
            'time_slot': forms.Select(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'phone_number': forms.TextInput(attrs={'class': 'form-control', 'type': 'tel'}),
            'allergy': forms.Textarea(attrs={'rows': 3, 'class': 'form-control'}),
        }


    def clean(self):
        # checks all fields, including the max_guests that day,date not in the past.   
        cleaned_data = super().clean()
        booking_date = cleaned_data.get('date')
        booking_time_slot = cleaned_data.get('time_slot')
        number_of_guests = cleaned_data.get('number_of_guests')
        max_guests = 20
        now = datetime.now()

        
        # checking if the date is in the past
        if booking_date and booking_date < now.date():
            raise ValidationError("Booking date cannot be in the past.")

        

        return cleaned_data

        # Check if the booking exceeds the maximum number of guests
        existing_bookings_count = Bookings.objects.filter(
            date=booking_date, time=booking_time
        ).aggregate(total_guests=models.Sum('number_of_guests'))['total_guests'] or 0

        

        if existing_bookings_count + number_of_guests > max_guests:
            raise ValidationError("Sorry, fully booked! Please choose another time or date.")

        return cleaned_data

bookings/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .forms import BookingsForm
from .models import Bookings
from django.conf import settings


# Create your views here.


@login_required
def booking_dashboard_view(request):    
    # Access only for logged in users
    user_bookings = Bookings.objects.filter(user=request.user)
    context = {
        'on_dashboard_page': True,
        'bookings': user_bookings,
        'GOOGLE_API_KEY': settings.GOOGLE_API_KEY,
    }
    return render(request, 'bookings/booking_dashboard.html', context)


    
def make_booking_view(request):
    # Checking for submission, using the BookingForm
    if request.method == 'POST':
        form = BookingsForm(request.POST)
        if form.is_valid():
            booking = form.save(commit=False)            
            booking.user = request.user
            booking.save()
            return redirect('bookings:booking_confirmation', booking_id=booking.id)            
    else:
        form = BookingsForm()
        context = {
        'form': form,
        'GOOGLE_API_KEY': settings.GOOGLE_API_KEY
    }
    return render(request, 'bookings/make_booking_form.html', context)





@login_required
def booking_confirmation(request, booking_id):
    # Passing the booking_id to user that is logged in, and displays it 
    booking = get_object_or_404(Bookings, id=booking_id, user=request.user)
    return render(request, 'bookings/booking_confirmation.html', {'booking': booking})



    
@login_required
def edit_booking_view(request, booking_id):    
    # Allows logged in users to edit booking based on booking_id
    booking = get_object_or_404(Bookings, id=booking_id, user=request.user)
    if request.method == 'POST':
        form = BookingsForm(request.POST, instance=booking)
        if form.is_valid():
            form.save()
            return redirect('bookings:booking_dashboard')
    else:
        form = BookingsForm(instance=booking)
        context = {
        'form': form,
        'booking': booking,
        'GOOGLE_API_KEY': settings.GOOGLE_API_KEY
    }
    return render(request, 'bookings/edit_booking.html', context)
        
    
   



@login_required
def cancel_booking_view(request, booking_id):
    # Deletes the booking based on the booking_id  and logged in user
    booking = get_object_or_404(Bookings, id=booking_id, user=request.user)
    booking.delete()  
    return redirect('bookings:booking_dashboard')

bookings/templates/bookings/booking_confirmation.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
<div class="container mt-3">
    <div class="card" style="max-width: 18rem;">
        <div class="card-body">
            <h5 class="card-title text-center">Your Booking Confirmation</h5>
            
<table class="table">
    <tbody>
        <tr>
            <th scope="row">Name:</th>
             <td class="text-end">{{ booking.first_name|default:"Not specified" }}
                 {{ booking.last_name|default:"" }}
             </td>
        </tr>
         <tr>
            <th scope="row">Number of Guests:</th>
            <td class="text-end">{{ booking.number_of_guests|default:"Not specified" }}</td>
         </tr>
         <tr>
            <th scope="row">Date</th>
            <td class="text-end">{{ booking.date|date:"Y-m-d" }}</td>
        </tr>
            <tr>
            <th scope="row">Time:</th>
            <td class="text-end">{{ booking.get_time_slot_display }}</td>
        </tr>
        <tr>
            <th scope="row">Contact Email:</th>
            <td class="text-end">{{ booking.email|default:"Not specified" }}</td>
         </tr>
        </tbody>
    </table>
            <div class="text-center">
                <a href="{% url 'bookings:booking_dashboard' %}" class="btn btn-secondary btn-sm">Return to Dashboard</a>
            </div>
        </div>
    </div>
</div>


{% endblock %}

bookings/templates/bookings/booking_dashboard.html
{% extends 'base.html' %}

{% load django_bootstrap5 %}


{% block content %}
<div class="container mt-3 booking-dash">
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Booking DashBoard</h5>

            <p>Welcome, {{ request.user.username }}</p>

            
            {% if bookings %}

            {% for booking in bookings %}

            <table class="table text-center">
                <tr>
                    <th scope="row" class="text-start">Name:</th>

                    <td class="text-end">{{ booking.first_name|default:"Not specified" }} {{ booking.last_name|default:"" }}</td>

                </tr>
                <tr>
                    <th scope="row" class="text-start">Number of Guests:</th>

                    <td class="text-end">{{ booking.number_of_guests|default:"Not specified" }}</td>

                </tr>
                <tr>

                    <th scope="row" class="text-start">Date</th>
                    <td class="text-end">{{ booking.date|date:"Y-m-d" }}</td>
                </tr>
                    <tr>
                    <th scope="row" class="text-start">Time:</th>
                    <td class="text-end">{{ booking.get_time_slot_display }}</td>
                </tr>
                </tr>
                <tr>

                    <th scope="row" class="text-start">Contact Email:</th>

                    <td class="text-end">{{ booking.email|default:"Not specified" }}</td>

                </tr>
            </table>


            <a href="{% url 'bookings:edit_booking' booking_id=booking.id %}" class="btn btn-outline-dark btn-sm">Edit
                this booking</a>

            <button class="btn btn-outline-dark btn-sm" data-bs-toggle="modal"
                data-bs-target="#yousure{{ booking.id }}">Cancel</button>

            <div class="modal fade" id="yousure{{ booking.id }}" tabindex="-1"
                aria-labelledby="CancelBookingModalAreYouSure" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title">Cancel your booking?</h5>
                        </div>
                        <div class="modal-body">
                            <p>Are you sure you want to cancel this booking?</p>
                        </div>
                        <div class="modal-footer">
                            <a href="{% url 'bookings:cancel_booking' booking_id=booking.id %}"
                                class="btn btn-danger btn-sm">Yes</a>
                            <button type="button" class="btn btn-secondary btn-sm" data-bs-dismiss="modal">No</button>
                        </div>
                    </div>
                </div>
            </div>

            {% endfor %}

            {% else %}
            <a href="{% url 'bookings:make_booking' %}" class="btn BTN-BLUE btn-lg">Book a table</a>
            {% endif %}

            <a href="{% url 'accounts:logout' %}" class="btn BTN-RED btn-lg">Logout</a>

        </div>
    </div>
</div>


{% endblock %}

bookings/templates/bookings/edit_booking.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}

<div class="container mt-3">

    <div class="card">
        
        <div class="card-body">
            
            <h5 class="card-title">Edit your booking {{ request.user.username }}</h5>
            <form method="post" action="{% url 'bookings:edit_booking' booking_id=booking.id %}" class="form">

                {% csrf_token %}
                {% bootstrap_form form %}

                <div class="d-grid gap-2">
                    <button type="submit" class="btn btn-success">Save Booking</button>

                    <a href="{% url 'bookings:booking_dashboard' %}" class="btn btn-secondary btn-sm">Return to Dashboard</a>

                </div>


            </form>
        </div>
    </div>
</div>

{% endblock %}

bookings/templates/bookings/make_booking_form.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block content %}


<div class="card col-12 col-sm-12 col-md-8 col-lg-3"><br>
    <h4 class="card-title">Book a table!</h4>
    <div class="card-body">
        <form method="post" action="{% url 'bookings:make_booking' %}" class="row g-2">
            {% csrf_token %}

            {% for field in form %}
                <div class="mb-3">

                    <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                    
                    {{ field }}

                    {% if field.help_text %}

                        <div class="form-text">{{ field.help_text }}</div>
                    
                        {% endif %}

                    {% for error in field.errors %}

                        <div class="invalid-feedback">

                            {{ error }}

                        </div>
                    {% endfor %}
                </div>
            {% endfor %}

            {% bootstrap_form_errors form type='all' %}
        
            <div class="d-grid gap-1">
                <button type="submit" class="btn btn-success btn-sm">Book Table</button>
                <a href="{% url 'bookings:booking_dashboard' %}" class="btn btn-secondary btn-sm">Return to Dashboard</a>
            </div>
        </form>
        </div>
        <div>
        </div>
</div>



{% endblock %}