accounts/urls.py
from django.urls import path, include
from . import views

app_name = 'accounts'

urlpatterns = [

    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'), 
    path('logout/', views.Logout_View, name='logout'),

]

backend/urls.py
from django.contrib import admin
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontend.urls', namespace='frontend')), 
    path('accounts/', include('accounts.urls', namespace='accounts')), 
    path('bookings/', include('bookings.urls', namespace='bookings')), 
    path('menu/', include('menu.urls', namespace='menu')), 
]

bookings/urls.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from django.contrib.auth.decorators import login_required
from django.urls import path
from . import views

app_name = 'bookings'

urlpatterns = [
 
    path('booking_dashboard/', views.booking_dashboard_view, name='booking_dashboard'),     
    path('make_booking/', views.make_booking_view, name='make_booking'),
    path('edit_booking/<int:booking_id>/', views.edit_booking_view, name='edit_booking'),     
    path('confirmation/<int:booking_id>/', views.booking_confirmation, name='booking_confirmation'),
    path('cancel/<int:booking_id>/', views.cancel_booking_view, name='cancel_booking'),
    
]

frontend/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views  

# Create your views here.

app_name = 'frontend'


urlpatterns = [

 path('', views.index, name='index'), 
 path('terms/', views.terms, name='terms'),
 path('privacy/', views.privacy, name='privacy'),

]

menu/urls.py
from django.urls import path, include
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from . import views

app_name = 'menu'

urlpatterns = [
    path('menu/', views.menu_view, name='menu'),
    path('recipe/', views.recipe_view, name='recipe'),
    path('gallery/', views.gallery_view, name='gallery'),
]

frontend/views.py
from django.conf import settings
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse


# Create your views here.




def index(request):
    # Getting the maps api key, from settings / rendering the landingpage
    context = {'GOOGLE_API_KEY': settings.GOOGLE_API_KEY}
    return render(request, 'index.html', context)

def terms(request):
     return render(request,'terms.html')


def privacy(request):
     return render(request,'privacy.html')

frontend/templates/base.html
<!DOCTYPE html>
<html lang="en">    
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Fine dining,eating in the canopy,good food,restaurant,forest,lake">
    <link rel="preload" href="https://fonts.googleapis.com/css2?family=Nunito&family=Roboto+Mono&display=swap" as="style">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito&family=Roboto+Mono&display=swap">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    <title>WoodHouse Bookings</title>
</head>

<body>

    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">

                <a class="navbar-brand" href="{% url 'frontend:index' %}">
                    <img src="https://res.cloudinary.com/dgve5ifit/image/upload/v1701268848/ge6xjqjp2klwvdujkbz0_vdh35l.webp"
                        alt="logo image" style="width:70px; height:70px;">
                    <h1 class="header-heading">WoodHouse Bookings</h1>
                </a>
                <button class="navbar-toggler bg-transparent" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a href="{% url 'menu:menu' %}" class="nav-link" aria-label="dinner menu">Menu</a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link" data-bs-toggle="modal"
                                data-bs-target="#galleryModal" aria-label="Gallery" role="button">Gallery</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'menu:recipe' %}" class="nav-link" aria-label="recipe link">Recipes</a>
                        </li>
                    </ul>
                    <div class="d-flex justify-content-center justify-content-lg-end soocial-icons">

                        <a href="http://www.facebook.com" class="nav-link" aria-label="link to facebook">
                            <i class="fa-brands fa-square-facebook"></i></a>

                        <a href="http://www.pinterest.com" class="nav-link" aria-label="link to pinterest"><i
                                class="fa-brands fa-square-pinterest"></i></a>

                        <a href="http://www.github.com" class="nav-link" aria-label="link to github"><i class="fa-brands fa-github"></i></a>

                        <a href="http://www.x.com" class="nav-link" aria-label="link to twitter now x"><i class="fa-solid fa-x"></i></a>
                    </div>

                </div>
            </div>
                        
        </nav>

    </header>

    {% block navbar %}

    {% if not request.user.is_authenticated %}
    <nav class="navbar navbar-light bg-light button-header">
        <div class="container-fluid">
            <span class="d-flex justify-content-center">
                <a href="{% url 'accounts:signup' %}" class="btn BTN-BLUE lg me-3">Sign up</a>
                <a href="{% url 'accounts:login' %}" class="btn BTN-BLUE lg">Login</a>
            </span>
        </div>        
    </nav>
    {% else %}
    {% if not on_dashboard_page %}

            <nav class="navbar navbar-light bg-light button-header">

                <div class="container-fluid">

                    <span class="d-flex justify-content-center">

                        <a href="{% url 'bookings:booking_dashboard' %}" class="btn btn-success btn-lg">Return to Dashboard</a>

                    </span>

                </div>

            </nav>
            {% endif %}
        {% endif %}

    {% endblock %}

    <main class="py-4">
        {% block content %}





        {% endblock %}
    </main>
    <footer class="text-center">
        <div class="container">
            <div class="row">

                <div class="col-12 col-md-4 d-flex flex-column justify-content-center text-center mb-3" id="address-section">
                    <h5>Woodhouse Bookings</h5>
                    <address>                        
                        4500 Pine Tree Lane,<br>
                        Woodland, WH<br>
                        P: (+46) 00 10 20 30<br>
                    </address>
                    <p>&copy; 2023 Woodhouse Bookings Ltd. All rights reserved.</p>
                    <p>
                        <a href="#" class="link-terms-policy" data-bs-toggle="modal" data-bs-target="#termsModal" role="button">
                            Terms of Service
                        </a>
                        |
                        <a href="#" class="link-terms-policy" data-bs-toggle="modal"
                            data-bs-target="#privacyModal" role="button">
                            Privacy Policy
                        </a>
                    </p>
                </div>

                <div class="col-12 col-md-4 d-flex flex-column justify-content-center text-center mb-3"
                    id="map-section">
                    <h5>Where to find us.</h5>
                    <p>Middle of the woods.</p>
                    <div id="map"></div>
                </div>


                <div class="col-12 col-md-4 d-flex flex-column justify-content-center text-center mb-3">
                    <h5>Contact Us</h5>
                    <p>Get in touch with our team</p>                    
                     <form id="contact-form" method="post">                    
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-12 mb-3">
                                <label for="contact-name"></label>
                                <input type="text" id="contact-name" name="from_name" class="form-control"
                                    placeholder="Your Name" required aria-label="Your full name"> 
                                
                            </div>
                            <div class="col-12 mb-3">
                                <label for="contact-email"></label>
                                <input type="email" id="contact-email" name="contact_email" class="form-control"
                                    placeholder="Your Email" required aria-label="Your email adress">
                                
                            </div>
                            <div class="col-12 mb-3">
                                <label for="contact-message"></label>
                                <textarea class="form-control" id="contact-message" name="message"
                                    placeholder="Your Message" rows="3" required aria-label="Your message"></textarea>
                                
                            </div>
                        </div>
                        <button type="submit" class="btn BTN-BLUE btn-sm">Send Message</button>
                        <div id="success-alert" class="alert alert-success fail-alert" role="alert"
                            style="margin-top:10px; display: none;">
                            Message Sent...
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </footer>




    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/97d1638932.js" crossorigin="anonymous"></script>    
    <script src="{% static 'js/maps.js' %}"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key={{ GOOGLE_API_KEY }}&callback=initMap"></script>
        <script src="{% static 'js/script.js' %}"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/@emailjs/browser@3/dist/email.min.js"></script>    

    {% include "terms.html" %}
    {% include "privacy.html" %}
    {% include 'gallery.html' %}


</body>

</html>

frontend/templates/index.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<div class="container section-background">
    
    <div class="row justify-content-start justify-content-md-center">
        <div class="col-lg-8">

            <div class="row">

                <div class="col-md-6 upcoming-events">

                    <article>
                        <h2>Upcoming Events</h2>
                        <p>26 NOV</p>
                        <p>Open Bar EVERY SUNDAY !!!</p>
                    </article>
                    <img src="https://res.cloudinary.com/dgve5ifit/image/upload/v1701177420/static/images/pexels-pixabay-274192_j3fi5z.webp" alt="busy bar night" style="width: 350px; height: 300px;">
                </div>


                <div class="col-md-6 abous-us">

                    <h2>About Us</h2>
                    
                    <p>In 1997, nestled within a quiet forest, a chef transformed a simple
                        childhood treehouse
                        into a unique treetop restaurant.</p>
                    
                        <p>Once a secret spot of joy, it was refurbished in 2021,
                        and it’s now a cozy dining place where delicious meals bring back sweet memories among
                        rustling leaves.</p>
                    
                        <p>With a mix of rustic charm and tasty dishes, it offers a memorable
                        dining experience under the stars.</p>
                </div>
            
            </div>
        </div>

    </div>
</div>

{% endblock content %}

frontend/templates/shared_index.html
{% block content %}

<div class="container section-background">
    
    <div class="row justify-content-start justify-content-md-center">
        <div class="col-lg-8">

            <div class="row">

                <div class="col-md-6 upcoming-events">

                    <article>
                        <h2>Upcoming Events</h2>
                        <p>26 NOV</p>
                        <p>Open Bar EVERY SUNDAY !!!</p>
                    </article>
                    <img src="https://res.cloudinary.com/dgve5ifit/image/upload/v1701177420/static/images/pexels-pixabay-274192_j3fi5z.webp" alt="busy bar night" style="width: 350px; height: 300px;">
                </div>


                <div class="col-md-6 abous-us">

                    <h2>About Us</h2>
                    
                    <p>In 1997, nestled within a quiet forest, a chef transformed a simple
                        childhood treehouse
                        into a unique treetop restaurant.</p>
                    
                        <p>Once a secret spot of joy, it was refurbished in 2021,
                        and it’s now a cozy dining place where delicious meals bring back sweet memories among
                        rustling leaves.</p>
                    
                        <p>With a mix of rustic charm and tasty dishes, it offers a memorable
                        dining experience under the stars.</p>
                </div>
            
            </div>
        </div>

    </div>
</div>
{% endblock content %}